Repository isogeo/isogeo-plugin-qgis, pull requests merged in 2019-10, with the labels that each got.

#260 Fix authentication and improve interactions with the API
  .gitignore
  isogeo.py
  modules/__init__.py
  modules/api/auth.py
  modules/api/request.py
  modules/api/reset_qsettings.py
  modules/api/shares.py
  modules/isogeo_pysdk/samples/__init__.py
  modules/isogeo_pysdk/samples/attributes_frequency.py
  modules/isogeo_pysdk/samples/dev_perfs_sync_async.py
  modules/isogeo_pysdk/samples/download_batch_hosted_data.py
  modules/isogeo_pysdk/samples/export_batch_xml19139_sync.py
  modules/isogeo_pysdk/samples/get_OpenCatalog.py
  modules/isogeo_pysdk/samples/latest_md_modified.py
  modules/isogeo_pysdk/samples/related_links.py
  modules/isogeo_pysdk/samples/results_parser.py
  modules/isogeo_pysdk/samples/search.py
  modules/isogeo_pysdk/samples/spatial_search.py
  modules/isogeo_pysdk/samples/store_api_responses.py
  modules/isogeo_pysdk/samples/udata_client_datagouvfr.py
  modules/tools.py
  modules/user_inform.py
  ui/auth/ui_authentication.ui
Labels: bug, enhancement

#268 last fixes before v2-beta3
  modules/api/auth.py
  modules/api/request.py
  modules/api/reset_qsettings.py
  modules/api/shares.py
  modules/search_form.py
  modules/tools.py
  modules/user_inform.py
Labels: bug, code art

#269 Adding layer from PostGIS table
  isogeo.py
  modules/layer/add_layer.py
  modules/layer/metadata_sync.py
  modules/results/display.py
  modules/tools.py
Labels: bug

#270 update authentication
  isogeo.py
  modules/api/auth.py
  modules/user_inform.py
Labels: enhancement

#282 Update OGC and ESRI services issues handling
  i18n/isogeo.qph
  i18n/isogeo_search_engine_fr.qm
  i18n/isogeo_search_engine_fr.ts
Labels: User Interface, bug

#275 Update api requesting issue catching
  isogeo.py
  modules/api/request.py
  modules/search_form.py
  modules/tools.py
  modules/user_inform.py
Labels: bug, enhancement

#278 Update results display
  modules/results/display.py
  modules/search_form.py
  modules/tools.py
Labels: User Interface, bug, enhancement

#290 Make Isogeo's API requesting work with QGIS 3.4 & 3.8
  modules/api/request.py
Labels: PyQGIS, bug, task

#289 Improve Proxy detection
  .vscode/settings.json
  Pipfile
  i18n/isogeo_search_engine_en.ts
  i18n/isogeo_search_engine_fr.ts
  isogeo.py
  modules/api/auth.py
  modules/api/request.py
  modules/tools.py
Labels: code art, enhancement

#292 Handle credentials file stored on a different disk drive
  modules/api/auth.py
Labels: enhancement

#293 pre-release 3.0.0
  .gitignore
  i18n/isogeo.qph
  i18n/isogeo_search_engine_en.ts
  i18n/isogeo_search_engine_fr.qm
  i18n/isogeo_search_engine_fr.ts
  metadata.txt
  modules/api/auth.py
  modules/api/request.py
  modules/results/display.py
  modules/tools.py
  modules/user_inform.py
Labels: code art, enhancement

#297 pre-release 3.0.1
  i18n/isogeo.qph
  i18n/isogeo_search_engine_en.ts
  i18n/isogeo_search_engine_fr.qm
  i18n/isogeo_search_engine_fr.ts
  isogeo.py
  metadata.txt
  modules/api/request.py
  modules/api/shares.py
  modules/layer/add_layer.py
  modules/user_inform.py
Labels: User Interface, bug, task
